# -*- coding: utf-8 -*-
"""project118.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17qr9Wr6tluMaw17aMgDeeXalG7nMK60v
"""

from google.colab import files
data_to_load = files.upload()

import pandas as pd
import plotly.express as px
df = pd.read_csv("stars.csv")
print(df.head())
fig = px.scatter(df,x = "Size",y = "Light")
fig.show()

from sklearn.cluster import KMeans
x = df.iloc[:,[0,1]].values
print(x)

wcss = []
for i in range(1,11):
  km = KMeans(n_clusters=i,init = "k-means++",random_state = 42)
  km.fit(x)
  wcss.append(km.inertia_)

import matplotlib.pyplot as plt
import seaborn as sb
plt.figure(figsize = (10,5))
sb.lineplot(range(1,11),wcss,marker = 'o',color = "red")
plt.title("elbowmethod")
plt.xlabel("light")
plt.ylabel("size")
plt.show()

km = KMeans(n_clusters = 3,init = "k-means++",random_state = 42)
ykmeans = km.fit_predict(x)

plt.figure(figsize = (15,7))
sb.scatterplot(x[ykmeans == 0,0],x[ykmeans == 0,1],color = "yellow",label = "cluster1")
sb.scatterplot(x[ykmeans == 1,0],x[ykmeans == 1,1],color = "blue",label = "cluster2")
sb.scatterplot(x[ykmeans == 2,0],x[ykmeans == 2,1],color = "green",label = "cluster3")
sb.scatterplot(km.cluster_centers_[:,0],km.cluster_centers_[:,1],color = "red",label = "centroids",s = 100,marker = ",")
plt.grid(False)
plt.title("stars")
plt.xlabel("size")
plt.ylabel("light")
plt.show()